import Head from "next/head";
import Selecct from "../componet/Select";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../images/logo.png" />
      </Head>

      <Selecct />
    </div>
  );
}
